### ISSUE TITLE
Fail to start ZAP with weekly build

### ISSUE THREAD

**Issue by msignoriniIon** [pdsoftplan/zap-maven-plugin#1]
In order to launch the local ZAP proxy, the ZapLocalBoot#retrieveZapJarName(String path) tries to find the jar file to use in the command line. The check performed in that method is too simple: it checks for the first file with ".jar" suffix.

With the weekly builds of ZAP, the above check fails because there are two Jars files and the above code selects the wrong one.

A new "zapVersion" configuration parameter can be accepted in order to force the jar file name.
From the build.xml file of ZAP I can see that the name of the zap jar is zap-<version>.jar

Row 714 of build.xml
<property name="zap.jar" value="zap-${version}.jar" /> 

Is it a valid enhancement request?

**Comment by tfcporciuncula** [comment]
The code is indeed too simplistic, thank you for opening this issue! This is definitely a valid enhancement request. The good thing about this problem is that we can easily fix it by removing or renaming any unrelated JAR files that happen to be within ZAP's folder (the weekly builds include the API JAR file, so we can just remove that to fix it).

But we should definitely improve our plugin to handle this kind of situation. However, instead of adding a new configuration parameter (we have too many already), I'd rather if the plugin could automatically choose the correct JAR. It would ignore any unrelated JAR file found (like the API JAR) and it would be able to choose the newest JAR, in case different versions of ZAP JAR files are present, which is a highly uncommon situation. Normally, if you have different versions of ZAP installed, each version will have its own folder, so if you want to run on another version you'd have to change the _zapPath_ parameter, and that's another reason I don't think adding a _zapVersion_ parameter is the way to go.

Another idea would be to let the user append the JAR file to the _zapPath_ parameter itself. For instance: if the user provides "C:/ZAP" as the _zapPath_, then our plugin will figure out what is the correct JAR file. But the user would also be able to provide "C:/ZAP/the-jar-he-wants.jar", and in this case we would trust the user and try to run this JAR.

Either way, we'd have to make sure to make it clear to the user what is happening with clear log messages. What do you think? Feel free to give suggestions and send pull requests!

**Comment by msignoriniIon** [comment]
> Another idea would be to let the user append the JAR file to the zapPath parameter itself.

Probably this is the safest idea.

Trying to detect the right jar without having control on the zap build process may be hard to maintain.
